FROM openjdk:8-alpine

# ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
# sshd part
ENV HBASE_PREFIX=/usr/local/hbase/hbase
RUN mkdir -p /tmp/native && \
       mkdir -p /usr/local/hbase/hbase-tmp \     
       mkdir -p /usr/local/hbase && \
       apk --update add wget tar bash coreutils procps vim openssh openrc curl python && \
       ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key && \
       ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key && \
       ssh-keygen -q -N "" -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key && \
       ssh-keygen -q -N "" -t ed25519 -f /etc/ssh/ssh_host_ed25519_key && \
       ssh-keygen -q -N "" -t rsa -f /root/.ssh/id_rsa && \
       cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys && \
       passwd -u root
# wget -c https://mirrors.tuna.tsinghua.edu.cn/apache/hbase/2.1.7/hbase-2.1.7-bin.tar.gz
ADD config /root/.ssh/config
ADD start.sh /etc/start.sh
WORKDIR /usr/local/hbase

RUN wget https://mirrors.tuna.tsinghua.edu.cn/apache/hbase/2.1.7/hbase-2.1.7-bin.tar.gz && \
       tar -zxvf hbase-2.1.7-bin.tar.gz && rm hbase-2.1.7-bin.tar.gz && \
       mv hbase-2.1.7 hbase && \
       chmod 764 $HBASE_PREFIX/conf/hbase-env.sh && \
       sed -i '/^export JAVA_HOME/ s:.*:export JAVA_HOME=/usr/lib/jvm/java-1.8-openjd\n:' $HBASE_PREFIX/conf/hbase-env.sh  && \
       chmod 700 /etc/start.sh 
# ssh 远程连接后系统 JAVA_HOME 环境变量会失效，这边直接定义一下
ADD hbase-site.xml $HBASE_PREFIX/conf/hbase-site.xml

# Hbase ports
EXPOSE 2181 8082 8085 9090 9095 16000 16010 16201 16301

ENTRYPOINT ["/etc/start.sh"]